name:                haddock-tutorial
version:             0.1.0.0
github:              "githubuser/haddock-tutorial"
license:             BSD3
author:              "Fintan Halpenny"
maintainer:          "fintan.halpenny@gmail.com"
copyright:           "2018 Fintan Halpenny"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/haddock-tutorial#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - text

tests:
  doctest:
    main: Main.hs
    source-dirs:
      - test/doctest
    dependencies:
      - doctest
      - doctest-discover
      - haddock-tutorial
